### ISSUE TITLE
problem with lnd averages when using single-variable timeseries variables as input

### ISSUE THREAD

**Issue by bertinia** [NCAR/pyAverager#36]
There's a bug in the pyAverager when using single variable timeseries input with clm data. 
The same data works correctly when using history slice input data.

Here's the error:

```
'WATSAT'
Traceback (most recent call last):
  File "/glade/p/work/aliceb/sandboxes/dev/postprocessing/diagnostics/diagnostics/lnd/lnd_avg_generator.py", line 229, in callPyAverager
    PyAverager.run_pyAverager(pyAveSpecifier)
  File "/glade/p/work/aliceb/sandboxes/dev/postprocessing/cesm-env2/lib/python2.7/site-packages/pyaverager/PyAverager.py", line 28, in run_pyAverager
    return PyAverager(spec)
  File "/glade/p/work/aliceb/sandboxes/dev/postprocessing/cesm-env2/lib/python2.7/site-packages/pyaverager/PyAverager.py", line 41, in __init__
    self.compute_averages(spec)
  File "/glade/p/work/aliceb/sandboxes/dev/postprocessing/cesm-env2/lib/python2.7/site-packages/pyaverager/PyAverager.py", line 307, in compute_averages
    key,spec.clobber,spec.year0,spec.year1,ave_date2,collapse_dim=l_collapse_dim)
  File "/glade/p/work/aliceb/sandboxes/dev/postprocessing/cesm-env2/lib/python2.7/site-packages/pyaverager/climFileIO.py", line 446, in define_ave_file
```

The input data files, both history slice and single variable timeseries files can be found at:

> /glade2/scratch2/mvr/archive/B1850C5CN_2deg_brco2ramp/lnd/hist

and

> /glade2/scratch2/mvr/archive/B1850C5CN_2deg_brco2ramp/lnd/proc/tseries/month_1

A python post-processing caseroot setup is here with pyAverager output logs:

> /glade/p/work/aliceb/sandboxes/runs/B1850C5CN_2deg_brco2ramp

**Comment by bertinia** [comment]
The postprocessing caseroot with the timeseries output logs from the reshaper are
located here:
/glade2/scratch2/mvr/cesm-postprocess/B1850C5CN_2deg_brco2ramp

**Comment by sherimickelson** [comment]
Fixed in latest tag

It now ignores fields that do not exist in all files.
